Add draft of release blog post
coreruleset/website pull request #193
Opened 2024-10-29 19:41 UTC by RedXanadu

Add draft of release blog post covering the 4.8.0 and 3.3.7 releases.

2024-10-29 20:01 UTC, RedXanadu commented
The Lychee link checker is misbehaving again.

2024-10-29 21:42 UTC, fzipi requested changes
Just two small changes.

2024-10-29 21:42 UTC, fzipi commented on content/blog/2024-10-29-crs-versions-4-8-0-and-3-3-7-released.md
> +The OWASP ModSecurity Core Rule Set (CRS) team is pleased to announce the release of two new CRS versions: v4.8.0 and v3.3.7.
```suggestion
The OWASP CRS team is pleased to announce the release of two new CRS versions: v4.8.0 and v3.3.7.
```

2024-10-29 21:42 UTC, fzipi commented on content/blog/2024-10-29-crs-versions-4-8-0-and-3-3-7-released.md
> +Andrew Howe on behalf of the Core Rule Set development team
```suggestion
Andrew Howe on behalf of the CRS development team
```

2024-10-30 00:23 UTC, fzipi commented
I'll be removing the check for Swiss Post after merging this one.

2024-10-30 09:42 UTC, RedXanadu commented
Yep, yep, the changes are fine. Perhaps you can tell that I used a pre-name change release post as a template :sweat_smile:

2024-10-30 14:19 UTC, merged